### PR TITLE
Added DashBoard and Event Class

### LINKED ISSUE #24: Add dashboard

### PR DESCRIPTION
**Pull request by harshendrashah**
Fixes #24

### CODE REVIEW

**Comment by DipanshKhandelwal** [comment]
Have you tested it ? It isn't working. The app is crashing on calling the dashboard.

**Comment by DipanshKhandelwal** [comment]
Have you tested it ? It isn't working. The app is crashing on calling the dashboard.

**Comment by harshendrashah** [comment]
It is working on my phone.

**Comment by Monal5031** [comment]
@DipanshKhandelwal I think its better if we delete the local repo and setup everything again, to avoid any changes done locally mistakenly.

**Comment by DipanshKhandelwal** [comment]
@Monal5031 everything is good :+1:

**Pull request merged**
