### PR TITLE
Enabled Google Sign In

### PR DESCRIPTION
**Pull request by yashLadha**

### CODE REVIEW

**Comment by Monal5031** [comment]
@yashLadha sir we have a gmail id of TechFest I hope you used that one for creating the OAuth

**Comment by yashLadha** [comment]
I have used the ID of coding club @Monal5031

**Comment by Monal5031** [comment]
No, please use the techfest id, take the id password from katara sir

-------- Original Message --------

**Comment by yashLadha** [comment]
Share the necessary details in the doc. @Monal5031

**Comment by DipanshKhandelwal** [comment]
Solves #5

**Comment by DipanshKhandelwal** [comment]
solves #5

**Pull request merged**
